services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_sql_1234
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - /home/kenne/bsn-ci-cd/data/postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn-prod
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8.3.0
    volumes:
      - /home/kenne/bsn-ci-cd/data/mysql_keycloak:/var/lib/mysql
      - /home/kenne/bsn-ci-cd/docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_24_0_2
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://192.168.1.10:5432/keycloak_24_0_2
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: admin_sql_1234
      KC_HOST_NAME: 192.168.1.10
    networks:
      - spring-demo
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  bsn-api:
    container_name: book-sn-api
    image: kennegervais/bsn-api:latest
    expose:
      - "8088"
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.1.10:5432/book_social_network
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin_sql_1234
      - BSN_DATABASE_URL=jdbc:postgresql://192.168.1.10:5432/book_social_network
      - BSN_DATABASE_USERNAME=postgres
      - BSN_DATABASE_PASSWORD=admin_sql_1234
#      - BSN_DATABASE_URL=jdbc:postgresql://192.168.1.10:5435/book_social_network
#      - BSN_DATABASE_USERNAME=username
#      - BSN_DATABASE_PASSWORD=password
      - BSN_ACTIVATION_URL=http://book-sn-ui:80/activate-account
      - EMAIL_HOSTNAME=mail-dev-bsn
      - EMAIL_USER_NAME=kenne
      - EMAIL_PASSWORD=kenne
      - EMAIL_PORT=1025
      - PROFILE=prod
      - ACTIVE_PROFILE=prod
      - BSN_KEYCLOAK_ISSUER_URI=http://192.168.1.10:9090/realms/book-social-network
      - BSN_KEYCLOAK_JWK_URI=http://192.168.1.10:9090/realms/book-social-network/protocol/openid-connect/certs
      - BSN_JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B625645367566B5970
      - BSN_UI_ORIGIN=http://localhost:4200,http://192.168.1.10:4200,http://book-sn-ui:4200
    restart: unless-stopped
    volumes:
      - /home/kenne/bsn-ci-cd/uploads/users:/app/uploads/users
    networks:
      - spring-demo
    depends_on:
      - postgres

  bsn-ui:
    container_name: book-sn-ui
    image: kennegervais/bsn-ui:latest
    expose:
      - "80"
    ports:
      - "4200:80"
    networks:
      - spring-demo
    depends_on:
      - bsn-api
      - keycloak

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local