spring:
  datasource:
    url: ${BSN_DATABASE_URL:jdbc:postgresql://192.168.1.145:5433/book_social_network}
    username: ${BSN_DATABASE_USERNAME:username}
    password: ${BSN_DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOSTNAME:localhost}
    port: ${EMAIL_PORT:1025}
    username: ${EMAIL_USER_NAME:kenne}
    password: ${EMAIL_PASSWORD:kenne}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${BSN_KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/book-social-network}
          jwk-set-uri: ${BSN_KEYCLOAK_JWK_URI:http://localhost:9090/realms/book-social-network/protocol/openid-connect/certs}
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B625645367566B5970
      expiration: 86400000
  mailing:
    frontend:
      activation-url: ${BSN_ACTIVATION_URL:http://localhost:4200/activate-account}
  cors:
    origins: ${BSN_UI_ORIGIN:http://192.168.1.145:4200,http://localhost:4200}
  file:
    upload:
      photos:
        photos-output-path: ./uploads